README.md
centos-7-minimal.template
create_live_iso
handle-user-data

This patch is use to externalize bash script from kickstart so that it will be easy to develop and test.

Fix #12 Externalize bash scripts

---

Makefile
centos-7-minimal.template
scripts/cert-gen.sh
scripts/handle-user-data

Restart will now works for machine.

Fix #23 docker-machine restart fails with CentOS VM

---

scripts/handle-user-data

This patch uses `--bind` mount functionality to make sure partition data mounted to `/var/lib/origin` so openshift service works as expected. This approach doesn't need separate partition and not depend on symlink. 
More on `bind` mount: http://unix.stackexchange.com/questions/198590/what-is-a-bind-mount

Fix #37 Persistent storage for openshift configurations

---

rhel-7.template

This patch will enable rhel-push-plugin for docker.

Fix #43 Enable rhel-push-plugin and add Red Hat registry

---

Makefile

Fix the target `check_env` https://github.com/minishift/minishift-centos-iso/issues/51

Fix #51 Fix typo in Makefile for `check_env` target

---

Makefile
README.md
centos-7.template
rhel-7.template

This patch will enable release from make provided required token is available.
- Updated README
- Create version file
- Updated version info in templates.

Fix #53 Add release target to Makefile

---

Makefile

Fix #55 Typo in Makefile for iso_creation target

---

rhel-7.template

This patch will fix a typo which create issue to build rhel_iso.

Fix #57 Error to build RHEL iso using "make rhel_iso" command.

---

Makefile
centos-7.template
rhel-7.template

This patch will add timestamp in the iso so it will be easy to detect which is used.

Fix #52 Minishift ISO version and build information is missing

---

rhel-7.template

This patch will remove epel repo details from the template which we added to test our image against docker-machine without our provisioner was in place.

Fix #65 Remove epel repo details from RHEL template

---

centos-7.template
rhel-7.template

This patch will add kernel options to disable consistent network device naming.

Fix #67 disable consistent network device name

---

scripts/handle-user-data

This patch add minishift directory and symlink with persistent storage. 
Depend on: https://github.com/minishift/minishift/pull/261
Steps to test:
- Build the iso with this patch
- Get minishift binary from https://ci.appveyor.com/project/hferentschik/minishift-o61ou/build/138/artifacts
- run minishift against built images
- Create some test application on minishift or add a template
- stop minishift
- start minishift => you should have test application configuration or template persistent.

Issue #76 Create minishift directory symlink to accommodate --host-data-dir option

---

README.md
Vagrantfile
centos-7.template
rhel-7.template

Below patch will resolve issue around SELinux enforcing mode. Please test it out before we merge it.
Make sure if you are not using centos-7 then use vagrant way of creating image I did update the document because live-tools are very specific around which host we are using for creating the images.

Issue #1 Build the ISO with SELinux in enforcing mode

---

rhel-7.template

This patch will be a workaround for latest docker and also added required runc dependency to service file.

Fix #85 docker-1.12.5 break docker daemon and need docker-runc-current

---

centos-7.template

we now have docker latest version with CentOS and below patch will add required info to make it work.

Fix #89 docker version updated to centos tree

---

tests/test.py

This seems to fix #121 by restarting the instance with the same arguments

Fixes #121 Restart VM using the same arguments

---

Makefile
centos-7.template
rhel-7.template
scripts/yum-wrapper
tests/test.py

Deals with #116 
* It shows `unsupported` when trying to install
* Waits for confirmation before executing the actual `yum` command
* Allows confirmation to be overwritten by using `-y` in the command
Note:
Banner might need to be more prominent...

Issue #116 Show banner when installing packages using `yum`

---

centos-7.template
rhel-7.template
scripts/handle-user-data

Fixes #125 Symlink /opt to storage disk

---

Makefile
centos_ci.sh
scripts/handle-user-data
tests/test.sh

Fix #141 
Not a shell programmer. Let me know if tests can be improved.

Issue #141 Replace avocado based tests with shell scripts based test

---

rhel-7.template

Accidently handle user data gets triggered twice, as systemd unit and from rc.local.

Issue #200 Handle user data triggers twice

---

centos-7.template
rhel-7.template

... when containerized deployment is not available or not wished for.
Service is disable on start, as Minishift handles the lifecycle.
Note: needed for https://github.com/minishift/minishift/issues/201

Issue #231 add dnsmasq as fallback option
