- centos-7-minimal.ks
@LalatenduMohanty @hferentschik @budhrg try to use this kickstart file to generate iso and it will have docker running.
> Minimal kickstart file to start docker

- Vagrantfile
- centos-7-livedocker-backup.cfg
Also added CPU and RAM configurable bits to the Vagrantfile
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
> Issue #5 Remove docker bits from the KS file

- centos-7-minimal.ks
This patch will resolve locale issue and same way it happen to boot2docker iso.
> Fix #8 Make sure the right Locale is set

- centos-7-minimal.template
This patch will fix issue with kernel option which caused issue with xhyve driver.
> Fix #29 Investigate about kernel command options

- Makefile
This patch will fix osx iso issue.
> Fix #30 Add steps to makefile to create iso which works with OS-X

- centos-7.template
- rhel-7.template
This patch will fix hyperv ip issue. Also it contain a minor change in docker service file.
> Fix #27 'IP not found' error with Hyper-V hypervisor on Windows

- centos-7.template
- rhel-7.template
This patch will enable to run custom provisioner.
> Fix #49  Add 'minishift' as variant for custom provisioner

- rhel-7.template
> Fix #70: Update RHEL ISO password

- Makefile
- README.md
- rhel-7.template
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
> Issue #61: Adding cdk-entitlements RPM to RHEL ISO

- Makefile
> Update version info to beta.1 to prepare release

- Makefile
This will fix addition of major version of Distribution.
> Fix #75 The ISO name should contain the major version of Distribution

- centos_ci.sh
@hferentschik @praveenkumar This PR integrate with CI
> Issue #21 Create a CI setup for the image build

- README.md
> Issue #92 Add build status of CentOS CI in README

- centos-7.template
- rhel-7.template
- tests/test.py
> Fix #98 Add cifs-utils for mounting smb shares

- scripts/handle-user-data
- tests/test.py
> Issue #96 Move swapon to mount function

- Makefile
> Issue #102 Fix ISO name in release target

- README.md
> Issue #128 Add community related instructions

- scripts/handle-user-data
- tests/test.py
> Fixes #136 Change docker symlinks to bind mount

- Vagrantfile
> Issue #159 perform a yum update during Vagrant provisioning

- scripts/set-ipaddress
use a generic name for consumption by minikube
> Issue #137 use generic naming for the network provision

- Makefile
This will help in downstream image build where we only need to generate kickstart file and then pass it to build system.
> Issue #181 adding kickstart target for rhel/centos

- Makefile
@LalatenduMohanty @gbraad This actually do the job. Apologize to having an bad PR in :(
> Issue #181 Add kickstart target for centos/RHEL

- centos-7.template
- rhel-7.template
Another attempt to clean kickstart file a bit.
> Issue #156 Add specific changes to docker systemd unit file instead creating new one.

- README.md
> Issue #187 Update README about tests not using 'Avocado' anymore

- centos-7.template
- rhel-7.template
> Issue #189 Add python-setuptools in install package list.

- centos_ci.sh
> Issue #194 Fix Github rate limit issue in CI

- centos-7.template
- rhel-7.template
- scripts/set-ipaddress
Fixes #180, #191 
Needed for allow multiple network configuration files: https://github.com/minishift/minishift/issues/1457
Signed-off-by: Gerard Braad <me@gbraad.nl>
> Issue #180 #191 Allow multiple network configuration files and support for RHEL

- scripts/handle-user-data
> Issue #198 Remove persisting /tmp directory

- centos_ci.sh
> Issue #166 Use packaged version of python-requests

- centos-7.template
- rhel-7.template
- scripts/handle-user-data
- tests/test.sh
> Issue #73 Add overlay as storage driver for docker instead devicemapper

- Makefile
- README.md
- centos_ci.sh
- scripts/release/issue-list.sh
Fix #178 
Tested the job here with https://ci.centos.org/job/minishift-centos-iso-release/6/console
using my github fork https://github.com/budhrg/minishift-centos-iso/releases/tag/v1.6.0
> Issue #178 Create release job

- centos-7.template
- rhel-7.template
- scripts/handle-user-data
- tests/test.sh
> Issue #226 RHEL ISO failing due to docker version update to 1.13.1

- rhel-7.template
> Issue #237 Removing dhclient-script override

- scripts/handle-user-data
- tests/test.sh
Fixes #240 (related to the use of OpenShift 3.10)
> Issue #240 Create bind mount for /var/lib/origin

- scripts/handle-user-data
- tests/test.sh
> Issue #253 Mount /etc/docker from persistent storage

- centos-7.template
- rhel-7.template
> Issue #261 change timezone to UTC
